/*
Dùng câu lệnh SQL để tạo ra CSDL
*/

CREATE DATABASE QUAN_LI_BAN_HANG
GO

USE QUAN_LI_BAN_HANG
GO

CREATE TABLE NHA_CUNG_CAP (
	MACONGTY NVARCHAR(10) NOT NULL,
	TENCONGTY NVARCHAR(40) NOT NULL,
	TENGIAODICH NVARCHAR(30), 
	DIACHI NVARCHAR(50),
	DIENTHOAI NVARCHAR(15),
	FAX NVARCHAR(15),
	EMAIL NVARCHAR(30)
	CONSTRAINT pk_MACONGTY PRIMARY KEY(MACONGTY)
);

CREATE TABLE LOAI_HANG(
	MALOAIHANG NVARCHAR(10) NOT NULL,
	TENLOAIHANG NVARCHAR(40) NOT NULL,
	CONSTRAINT pk_MALOAIHANG PRIMARY KEY(MALOAIHANG)
);

CREATE TABLE MAT_HANG(
	MAHANG NVARCHAR(10) NOT NULL,
	TENHANG NVARCHAR(50) NOT NULL,
	MACONGTY NVARCHAR(10),
	MALOAIHANG NVARCHAR(10),
	SOLUONG INT,
	DONVITINH NVARCHAR(10),
	GIAHANG INT,
	CONSTRAINT pk_MAHANG PRIMARY KEY(MAHANG),
	CONSTRAINT fk_MACONGTY_NHA_CUNG_CAP FOREIGN KEY(MACONGTY) REFERENCES NHA_CUNG_CAP(MACONGTY),
	CONSTRAINT fk_MALOAIHANG_LOAI_HANG FOREIGN KEY(MALOAIHANG) REFERENCES LOAI_HANG(MALOAIHANG)
);

CREATE TABLE NHAN_VIEN(
	MANHANVIEN NVARCHAR(10) NOT NULL,
	HO NVARCHAR(20) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	NGAYSINH DATETIME,
	NGAYLAMVIEC DATETIME,
	DIACHI NVARCHAR(50),
	DIENTHOAI NVARCHAR(15),
	LUONGCOBAN INT,
	PHUCAP INT,
	CONSTRAINT pk_MANHANVIEN PRIMARY KEY(MANHANVIEN)
);

CREATE TABLE KHACH_HANG(
	MAKHACHHANG NVARCHAR(10) NOT NULL,
	TENCONGTY NVARCHAR(40) NOT NULL,
	TENGIAODICH NVARCHAR(30),
	DIACHI NVARCHAR(50),
	DIENTHOAI NVARCHAR(15),
	FAX NVARCHAR(15),
	EMAIL NVARCHAR(30),
	CONSTRAINT pk_MAKHACHHANG PRIMARY KEY(MAKHACHHANG)
);

CREATE TABLE DON_DAT_HANG(
	SOHOADON INT NOT NULL,
	MAKHACHHANG NVARCHAR(10),
	MANHANVIEN NVARCHAR(10),
	NGAYDATHANG DATETIME,
	NGAYGIAOHANG DATETIME,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG NVARCHAR(50),
	CONSTRAINT pk_SOHOADON PRIMARY KEY(SOHOADON),
	CONSTRAINT fk_MAKHACHHANG_KHACH_HANG FOREIGN KEY(MAKHACHHANG) REFERENCES KHACH_HANG(MAKHACHHANG),
	CONSTRAINT fk_MANHANVIEN_NHAN_VIEN FOREIGN KEY(MANHANVIEN) REFERENCES NHAN_VIEN(MANHANVIEN)
);

CREATE TABLE CHI_TIET_DAT_HANG(
	SOHOADON INT NOT NULL,
	MAHANG NVARCHAR(10),
	GIABAN INT,
	SOLUONG SMALLINT,
	MUCGIAMGIA NUMERIC(2,1),
	CONSTRAINT pk_CHI_TIET_DAT_HANG PRIMARY KEY(SOHOADON, MAHANG)
);

/* Bổ sung ràng buộc thiết lập giá trị mặc định bằng 1 cho cột SOLUONG và bằng 0
cho cột MUCGIAMGIA trong bảng CHITIETDATHANG */

ALTER TABLE CHI_TIET_DAT_HANG
ADD 
	CONSTRAINT df_CHI_TIET_DAT_HANG_SOLUONG DEFAULT(1) FOR SOLUONG

ALTER TABLE CHI_TIET_DAT_HANG
ADD 
	CONSTRAINT df_CHI_TIET_DAT_HANG_MUCGIAMGIA DEFAULT(0) FOR MUCGIAMGIA

/*
Bổ sung cho bảng DONDATHANG ràng buộc kiểm tra ngày giao hàng và ngày
chuyển hàng phải sau hoặc bằng với ngày đặt hàng
*/

ALTER TABLE DON_DAT_HANG
ADD
	CONSTRAINT ckeck_NGAY CHECK(NGAYGIAOHANG >= NGAYDATHANG AND NGAYCHUYENHANG >= NGAYDATHANG)

/*
Bổ sung ràng buộc cho bảng NHANVIEN để đảm bảo rằng một nhân viên chỉ có thể
làm việc trong công ty khi đủ 18 tuổi và không quá 60 tuổi.
*/

ALTER TABLE NHAN_VIEN
ADD
	CONSTRAINT check_AGE CHECK(YEAR(GETDATE()) - YEAR(NGAYSINH) BETWEEN 18 AND 60)

/*
K xóa được table nhà cung cấp vì nó có ràng buộc với các bảng khác,
nếu muốn xóa thì trước tiên phải xóa tất cả các ràng buộc trước
*/

/*
Cho biết danh sách các đối tác cung cấp hàng cho công ty
*/

SELECT TENCONGTY, MACONGTY FROM NHA_CUNG_CAP

/*
 Mã hàng, tên hàng và số lượng hiện có trong công ty
 */

 SELECT MAHANG, TENHANG, SOLUONG FROM MAT_HANG

 /*
Địa chỉ, số điện thoại của nhà cung cấp có tên giao dịch VINAMILK là gì?
*/
INSERT INTO NHA_CUNG_CAP(TENCONGTY, MACONGTY, DIACHI, DIENTHOAI,TENGIAODICH) VALUES(N'APPLE', N'APPLEE', N'VÂN DU', N'0396534215', N'VINAMILK');
INSERT INTO NHA_CUNG_CAP(TENCONGTY, MACONGTY, DIACHI, DIENTHOAI, TENGIAODICH) VALUES(N'SAMSUNG', N'SAMSUNGG', N'THÀNH MINH', N'0396534215', N'THTRUEMILK');
SELECT DIACHI, DIENTHOAI FROM NHA_CUNG_CAP WHERE TENGIAODICH = 'VINAMILK';
/*
Cho biết mã và tên các mặt hàng có giá lơn hơn 100000 và số lượng hiện có ít hơn 50
*/
INSERT INTO MAT_HANG(MAHANG, TENHANG, GIAHANG, SOLUONG) VALUES(N'MH001', N'MA TÚY', 1000000, 40)
INSERT INTO MAT_HANG(MAHANG, TENHANG, GIAHANG, SOLUONG) VALUES(N'MH002', N'THUỐC VIỆN', 10000, 40)
INSERT INTO MAT_HANG(MAHANG, TENHANG, GIAHANG, SOLUONG) VALUES(N'MH003', N'CẦN SA', 500000, 20)
SELECT MAHANG, TENHANG FROM MAT_HANG WHERE GIAHANG > 100000 AND SOLUONG < 50;

/*
Đơn đặt hàng số 1 do ai đặt, do nhân viên nào lập, thời gian và địa điểm giao hàng ở đâu?
*/
SELECT MANHANVIEN, NGAYGIAOHANG, NOIGIAOHANG, SOHOADON FROM DON_DAT_HANG WHERE SOHOADON = 1;
/*
Hiển thị những nhân viên có lương cơ bản cao nhất công ty
*/
INSERT INTO NHAN_VIEN(MANHANVIEN, HO, TEN, LUONGCOBAN) VALUES(N'NV001', N'BÙI', N'NGỌC TIẾN', 10000);
INSERT INTO NHAN_VIEN(MANHANVIEN, HO, TEN, LUONGCOBAN) VALUES(N'NV002', N'HÀ', N'TUẤN THÀNH', 1000);
INSERT INTO NHAN_VIEN(MANHANVIEN, HO, TEN, LUONGCOBAN) VALUES(N'NV003', N'TRỊNH', N'ĐỨC ANH', 5000);
INSERT INTO NHAN_VIEN(MANHANVIEN, HO, TEN, LUONGCOBAN) VALUES(N'NV004', N'BÙI', N'TRANG', 10000);
INSERT INTO NHAN_VIEN(MANHANVIEN, HO, TEN, LUONGCOBAN) VALUES(N'NV005', N'NGUYỄN', N'VĂN DƯƠNG', 2000);
SELECT HO, TEN , MAX(LUONGCOBAN) AS "MAX LƯƠNG" FROM NHAN_VIEN GROUP BY HO, TEN;
/*
Nhân viên nào trong công ty bán được nhiều hàng nhất và số lượng bán được là bao nhiêu?
*/

/*
Hãy cho biết tổng số hàng của mỗi loại hàng
*/

/*
Tăng lương lên 50% cho những nhân viên bán được số lượng hàng >=100 trong năm 2021.
*/

/*
Xóa những đơn hàng có ngày đặt hàng trước năm 2020 ra khỏi CSDL
*/

/*
Xóa khỏi bảng NHANVIEN những nhân viên đã làm việc cho công ty trên 40 năm
*/

/*
Xóa những đơn hàng có ngày đặt hàng trước năm 2020 ra khỏi CSDL
*/

/*
Xóa khỏi bảng NHANVIEN những nhân viên đã làm việc cho công ty trên 40 năm
*/